"Compiled on a Linux 2.6.12 system on 2009-09-18.\n"
"Available extensions:"
"	GNU libio by Per Bothner\n"
"	crypt add-on version 2.1 by Michael Glad and others\n"
"	linuxthreads-0.10 by Xavier Leroy\n"
"	BIND-8.2.3-T5B\n"
"	libthread_db work sponsored by Alpha Processor Inc\n"
"	NIS(YP)/NIS+ NSS modules 0.19 by Thorsten Kukuk\n"
"	software FPU emulation by Richard Henderson, Jakub Jelinek and others\n"
